### ISSUE TITLE
BUG: utimensat_time64 returns EPERM on x86_64 via an x86 binary

### ISSUE THREAD

**Issue by xantares** [seccomp/libseccomp#228] opened 2020-03-26 08:00 UTC
I have trouble running the futimens call of glibc(2.31) which ends up calling utimensat_time64 through docker via a 32 bits binary (using multilib gcc):

```
int main() {
  int fd = open("foo", O_RDWR | O_CREAT, 0644);
  write(fd, "foo", 3);
  struct timespec times[2] = {};
  times[0].tv_sec = 1;
  times[0].tv_nsec = 2;
  times[1].tv_sec = 3;
  times[1].tv_nsec = 4;
  int rc = futimens(fd, times);
  printf("rc=%d\n", rc);
  close(fd);
  return rc;
}
```

I'm using an archlinux 64 bits box with libseccomp 2.4.2 (I also tried git master):
```
$ uname -a
Linux arch64-001 5.5.11-arch1-1 #1 SMP PREEMPT Sun, 22 Mar 2020 16:33:15 +0000 x86_64 GNU/Linux
```

to reproduce the issue use https://github.com/xantares/test-seccomp-time64:
```
$ cd /tmp
$ git clone https://github.com/xantares/test-seccomp-time64.git
$ docker build test-seccomp-time64
openat(AT_FDCWD, "foo", O_RDWR|O_CREAT, 0644) = 3
write(3, "foo", 3)                      = 3
utimensat_time64(3, NULL, [{tv_sec=1, tv_nsec=2}, {tv_sec=3, tv_nsec=4}], 0) = -1 EPERM (Operation not permitted)
fstat64(1, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
...
close(3)                                = 0
write(1, "rc=-1\n", 6)                  = 6
exit_group(-1)                          = ?
```

however this is fine if I compile the binary in 64 bits mode (just remove the -m32 flag in Dockerfile).

**Comment by pcmoore** [comment] 2020-03-26 14:53
Hi @xantares, a couple of questions to help us understand your problems a bit better:
* What version of libseccomp are you using?
* Is your Docker configuration blocking this via Docker's libseccomp configuration?

**Comment by xantares** [comment] 2020-03-26 14:58
- it's libseccomp 2.4.2, but I also tried master
- I'm using docker with default settings from my distro, I think it's using libseccomp:
```
$ zcat /proc/config.gz | grep seccomp -i
CONFIG_SECCOMP=y
CONFIG_HAVE_ARCH_SECCOMP_FILTER=y
CONFIG_SECCOMP_FILTER=y
```

**Comment by pcmoore** [comment] 2020-03-26 15:13
If I'm understanding the Docker command line correctly, it looks like your reproducer works if you disable the seccomp filter, but it fails if you leave the default Docker seccomp filter enabled?

I'm not a docker expert, but looking at their seccomp profile (below) it appears as though they don't allow the `utimensat_time64()` syscall.
* https://github.com/moby/moby/blob/master/profiles/seccomp/default.json

I'm going to close this out as it appears to be a problem with the Docker configuration and not with libseccomp, but if you find that not to be the case and libseccomp is at fault, please let us know and reopen this issue.

**Comment by xantares** [comment] 2020-03-26 15:14
ok, thanks

**Closed by pcmoore** 2020-03-26 15:13 UTC
Labels: bug, pending/info, priority/low
