### ISSUE TITLE
BUG: some tests in 53-sim-binary_tree failed on Ubuntu Bionic i386 / s390x

### ISSUE THREAD

**Issue by Cypresslin** [seccomp/libseccomp#267] opened 2020-07-17 07:40 UTC
Hello,

while doing our SRU kernel regression tests, we have found that 30 tests in 53-sim-binary_tree will fail with the 4.15.0-111-generic Ubuntu Bionic i386 and s390x (passed with amd64 and PowerPC, skipped on ARM64).

With the following error message (s390x):

	batch name: 53-sim-binary_tree
	test mode: c
	test type: bpf-sim
	Test 53-sim-binary_tree%%001-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%002-00001 result: ERROR bpf_sim rc=14
	test arch: x86_64
	Test 53-sim-binary_tree%%003-00001 result: SUCCESS
	test arch: ppc64le
	Test 53-sim-binary_tree%%003-00001 result: SUCCESS
	Test 53-sim-binary_tree%%004-00001 result: SUCCESS
	Test 53-sim-binary_tree%%005-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%006-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%007-00001 result: ERROR bpf_sim rc=14
	test arch: x86_64
	Test 53-sim-binary_tree%%008-00001 result: SUCCESS
	test arch: ppc64le
	Test 53-sim-binary_tree%%008-00001 result: SUCCESS
	Test 53-sim-binary_tree%%009-00001 result: SUCCESS
	Test 53-sim-binary_tree%%010-00001 result: ERROR bpf_sim rc=14
	test arch: x86_64
	Test 53-sim-binary_tree%%011-00001 result: SUCCESS
	test arch: ppc64le
	Test 53-sim-binary_tree%%011-00001 result: SUCCESS
	Test 53-sim-binary_tree%%012-00001 result: SUCCESS
	test arch: x86_64
	Test 53-sim-binary_tree%%013-00001 result: SUCCESS
	test arch: ppc64le
	Test 53-sim-binary_tree%%013-00001 result: SUCCESS
	Test 53-sim-binary_tree%%014-00001 result: SUCCESS
	Test 53-sim-binary_tree%%015-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%016-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%017-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%018-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%019-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%020-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%021-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%022-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%023-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%024-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%025-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%026-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%027-00001 result: ERROR bpf_sim rc=14
	test arch: x86_64
	Test 53-sim-binary_tree%%028-00001 result: SUCCESS
	test arch: ppc64le
	Test 53-sim-binary_tree%%028-00001 result: SUCCESS
	Test 53-sim-binary_tree%%029-00001 result: SUCCESS
	test arch: x86_64
	Test 53-sim-binary_tree%%030-00001 result: SUCCESS
	test arch: ppc64le
	Test 53-sim-binary_tree%%030-00001 result: SUCCESS
	Test 53-sim-binary_tree%%031-00001 result: SUCCESS
	Test 53-sim-binary_tree%%032-00001 result: ERROR bpf_sim rc=14
	test arch: x86_64
	Test 53-sim-binary_tree%%033-00001 result: SUCCESS
	test arch: ppc64le
	Test 53-sim-binary_tree%%033-00001 result: SUCCESS
	Test 53-sim-binary_tree%%034-00001 result: SUCCESS
	Test 53-sim-binary_tree%%035-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%036-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%037-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%038-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%039-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%040-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%041-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%042-00001 result: ERROR bpf_sim rc=14
	test arch: x86_64
	Test 53-sim-binary_tree%%043-00001 result: SUCCESS
	test arch: ppc64le
	Test 53-sim-binary_tree%%043-00001 result: SUCCESS
	Test 53-sim-binary_tree%%044-00001 result: SUCCESS
	test arch: x86_64
	Test 53-sim-binary_tree%%045-00001 result: SUCCESS
	test arch: ppc64le
	Test 53-sim-binary_tree%%045-00001 result: SUCCESS
	Test 53-sim-binary_tree%%046-00001 result: SUCCESS
	Test 53-sim-binary_tree%%047-00001 result: ERROR bpf_sim rc=14
	Test 53-sim-binary_tree%%048-00001 result: ERROR bpf_sim rc=14
	test arch: x86_64
	Test 53-sim-binary_tree%%049-00001 result: SUCCESS
	test arch: ppc64le
	Test 53-sim-binary_tree%%049-00001 result: SUCCESS
	Test 53-sim-binary_tree%%050-00001 result: SUCCESS
	test mode: c
	test type: bpf-valgrind
	Test 53-sim-binary_tree%%051-00001 result: SUCCESS
	batch name: 54-live-binary_tree
	test mode: c
	test type: live
	Test 54-live-binary_tree%%001-00001 result: SKIPPED (must specify live tests)
	batch name: 55-basic-pfc_binary_tree
	test mode: c
	test type: basic
	Test 55-basic-pfc_binary_tree%%001-00001 result: SUCCESS
	batch name: 56-basic-iterate_syscalls
	test mode: c
	test type: basic
	Test 56-basic-iterate_syscalls%%001-00001 result: SUCCESS
	batch name: 57-basic-rawsysrc
	test mode: c
	test type: basic
	Test 57-basic-rawsysrc%%001-00001 result: SUCCESS
	batch name: 58-live-tsync_notify
	test mode: c
	test type: live
	Test 58-live-tsync_notify%%001-00001 result: SKIPPED (must specify live tests)
	Regression Test Summary
	tests run: 5354
	tests skipped: 81
	tests passed: 5324
	tests failed: 0
	tests errored: 30

The failures on i386 is a bit different:

    Test 53-sim-binary_tree%%001-00001 result: FAILURE bpf_sim resulted in KILL

But they all failing with the same test case.

A quick bisect shows this is the commit that causes this failure:

    0c94a019f5b4 tests: Handle pseudo-syscalls in the sim binary tree test

Or maybe we need some specific commit in our kernel?
Thanks

Bug report on launchpad: https://bugs.launchpad.net/ubuntu-kernel-tests/+bug/1886409

**Comment by drakenclimber** [comment] 2020-07-17 13:42
Thanks for the report @Cypresslin.  I'll look into it.

**Comment by pcmoore** [comment] 2020-07-17 14:39
Thanks @Cypresslin and @drakenclimber.  I'm going to hold off on marking this for the v2.5.0 release since we are *so* close and we know little about this bug or the root cause.

@drakenclimber please keep us updated and let us know the root cause as soon as you find it.

**Comment by drakenclimber** [comment] 2020-07-17 14:54
I'm testing the fix now.  Looks like I misunderstood the meaning of `all` in the *.tests file.

**Comment by drakenclimber** [comment] 2020-07-17 15:20
> @drakenclimber please keep us updated and let us know the root cause as soon as you find it.

As I alluded to above, I misunderstood `all` in the architecture column of the tests file.  In my mind, it was testing all architectures in the filter - not all architectures supported by libseccomp.  Oops.  So when the tests were run on s390x, the tests file was testing s390x syscalls against a filter that didn't contain any s390x syscalls.

So, it's an easy fix.  Simply find and replace `all` with `+x86_64,+ppc64le,+aarch64`.  The fix is running through TravisCI right now.

**Comment by pcmoore** [comment] 2020-07-17 15:51
Ah ha!  Thanks for the quick resolution @drakenclimber, since we know what the problem is (and presumably have a fix), I'm going to add this to the v2.5.0 milestone.

**Comment by drakenclimber** [comment] 2020-07-17 16:02
> Ah ha! Thanks for the quick resolution @drakenclimber, since we know what the problem is (and presumably have a fix), I'm going to add this to the v2.5.0 milestone.

Good call.  I think that's the right answer.

**Comment by pcmoore** [comment] 2020-07-18 00:48
Closing as this has been resolved in PR #268.

**Closed by pcmoore** 2020-07-18 00:48 UTC
Labels: bug, priority/medium
