### ISSUE TITLE
BUG: scmp_bpf_disasm.c doesn't support instructions with BPF_X at all

### ISSUE THREAD

**Issue by ymgve** [seccomp/libseccomp#101] opened 2017-11-05 10:33 UTC
Take for example these opcodes:

    0013: 0x15 0x04 0x05 0x00000001   jeq 1    true:0018 false:0019
    0014: 0x1d 0x04 0x00 0x0000000b   jeq 11   true:0019 false:0015

The second one is wrong, it should actually be

    0013: 0x15 0x04 0x05 0x00000001   jeq 1    true:0018 false:0019
    0014: 0x1d 0x04 0x00 0x0000000b   jeq x    true:0019 false:0015

**Comment by david942j** [comment] 2017-11-06 09:51
You should not file this issue during the CTF XD
sorry libseccomp authors, this issue becomes a challenge 😝

**Comment by pcmoore** [comment] 2017-11-07 20:46
Closing this issue, feel free to add a comment if you still have concerns.

**Closed by pcmoore** 2017-11-07 20:46 UTC

**Comment by ymgve** [comment] 2017-11-07 21:40
Why did you close it? Is it a wontfix? Because it clearly is a bug.

**Comment by pcmoore** [comment] 2017-11-07 22:03
> Why did you close it? Is it a wontfix? Because it clearly is a bug.

See @david942j's comment, it looks like this is part of some CTF competition?  Some clarity is needed from either you or David.

Also, it is important to note that we don't currently support the scmp_bpf_disasm tool outside of libseccomp (not installed during `make install`); it's a tool intended only for use by libseccomp developers.  This doesn't mean we won't fix bugs, but just that they are *extremely* low priority if the problem is with BPF that originates outside libseccomp.

**Comment by pcmoore** [comment] 2017-11-07 22:14
To further clarify, we don't currently use the BPF index register in libseccomp so the BPF_X opcode modifier is not necessary given the current libseccomp code.

**Comment by ymgve** [comment] 2017-11-07 22:16
The bug is real - a CTF challenge used it to obfuscate what was really going on in its seccomp filter. If the tool isn't intended to be used as a general purpose disassembler I guess that's a valid reason for low priority.

**Comment by pcmoore** [comment] 2017-11-07 22:30
See my earlier comment above about libseccomp not generating BPF code that uses BPF_X.
