### ISSUE TITLE
BUG: unable to call seccomp_load() more than once with v2.5.0

### ISSUE THREAD

**Issue by stoeckmann** [seccomp/libseccomp#273] opened 2020-07-23 18:10 UTC
Hi,

a user of xwallpaper noticed an issue with libseccomp 2.5.0, see here: https://github.com/stoeckmann/xwallpaper/issues/23

The tool xwallpaper calls seccomp_load twice during runtime to further tighten its sandbox during runtime. An example for "stage 1" sandbox would be opening files and only in "stage 2" these files would be parsed, not allowing further open calls etc.

I compared libseccomp 2.4.3 and 2.5.0 and figured out that 2.5.0 would add SECCOMP_FILTER_FLAG_NEW_LISTENER to seccomp call. When setting up the "stage 1" sandbox, everything is fine. The seccomp system call returns a file descriptor for the listener to use. But if "stage 2" is set up, SECCOMP_FILTER_FLAG_NEW_LISTENER is added again and seccomp returns -1 with EBUSY.

Forcefully denying SECCOMP_FILTER_FLAG_NEW_LISTENER by patching the code made xwallpaper functional again.

Since I am not implying that you should use a fullblown tool like xwallpaper to debug this issue, you can modify libseccomp-2.5.0/tests/52-basic-load.c to call seccomp_load twice, which makes it fail.

My understand is that seccomp_load is allowed to be called multiple times for exactly this kind of use case, i.e. adding more filters. Please let me know if I am mistaken here or if there is another way to add filter rules.

Thanks in advance!

**Comment by stoeckmann** [comment] 2020-07-23 18:13
The seccomp code in question is rather separated from other xwallpaper code parts, so you can see xwallpaper's libseccomp usage here: https://github.com/stoeckmann/xwallpaper/blob/master/seccomp.c

**Comment by pcmoore** [comment] 2020-07-23 18:27
Hi @stoeckmann, thanks for the bug report!  Yes, you are correct that we do allow `seccomp_load()` to be called multiples times.

We'll need to think about how we want to resolve this.

**Comment by pcmoore** [comment] 2020-07-23 18:33
@stoeckmann @drakenclimber, we still need to look at how the kernel handles multiple notification fd requests to make sure this is correct, but my initial thinking is that we may need to keep a global flag (yuck), which tracks if we've already requested a notification fd and if we have one, we don't request another.

Essentially we would be moving `notify_fd` from the filter context to a global value in "src/system.c".

**Comment by pcmoore** [comment] 2020-07-23 18:52
Building on my previous comment, we *might* want to allow a caller to request another notification fd on the odd chance that they did a `fork()` or a `clone()` after requesting a notification fd.  We really need to understand what the kernel does in these cases with respect to the notification fd.

If we need to handle this, we could always keep the `notify_fd` in the filter context while also keeping a global value.  On `seccomp_init()` the context would inherit the fd from the global value, but a `seccomp_reset()` would still reset it to `-1` while leaving the global value intact.  This would require a caller to do an init/reset for each filter after a fork where they wanted to request a new notification fd, but that seems like a reasonable compromise for such a niche use case.

**Comment by pcmoore** [comment] 2020-07-23 18:54
... or, maybe we allow a caller to call `seccomp_reset(NULL, ...)` instead of returning `-EINVAL`?  In this particular case, the NULL context, we would reset any global state, e.g. the saved notification fd.

**Comment by pcmoore** [comment] 2020-07-23 20:34
To close the loop on the kernel portion of this, yes, it looks like if any of the filters loaded into the current task have requested a notifier fd then the load operation fails with `-EBUSY`, see [kernel/seccomp.c:init_listener()](https://elixir.bootlin.com/linux/latest/C/ident/init_listener).

**Comment by brauner** [comment] 2020-07-23 20:37
> To close the loop on the kernel portion of this, yes, it looks like if any of the filters loaded into the current task have requested a notifier fd then the load operation fails with `-EBUSY`, see [kernel/seccomp.c:init_listener()](https://elixir.bootlin.com/linux/latest/C/ident/init_listener).

The seccomp notifier currently has the restriction that only a single fd can be requested. This prevents seccomp notify fd filters to override each other's decisions.

**Comment by pcmoore** [comment] 2020-07-23 20:47
@brauner yeah.

Do you anticipate the kernel's behavior changing in this regard anytime soon?  We need to figure out a way to support this in libseccomp and it would be helpful to know about any future or queued work so we don't end up painting ourselves into a corner API wise.

**Comment by brauner** [comment] 2020-07-23 22:18
> @brauner yeah.
> 
> Do you anticipate the kernel's behavior changing in this regard anytime soon? We need to figure out a way to support this in libseccomp and it would be helpful to know about any future or queued work so we don't end up painting ourselves into a corner API wise.

It has been brought up recently but no-one has actually made an argument why it's needed. So no, I don't think so. I think once we enable this we might need to revisit the "override" behavior.

**Comment by pcmoore** [comment] 2020-07-23 22:36
Okay, let me think on this for a bit, as well as get @drakenclimber's thoughts on the API, but my gut feeling is we probably want to solve this by stashing the notification fd in a global and providing the ability to reset/clear it via `seccomp_reset(NULL, ...)`.

**Comment by pcmoore** [comment] 2020-07-26 16:01
@drakenclimber  what do think of the approach in the commit below?
* https://github.com/pcmoore/misc-libseccomp/commit/0811440220aad949feb38428290f91f525742b1d

@stoeckmann the commit above should fix the problem you are seeing, if you could give it a test and report back that would be appreciated.

**Comment by stoeckmann** [comment] 2020-07-26 16:31
Hi @pcmoore,

just tested the commit. xwallpaper works with it again.

**Comment by pcmoore** [comment] 2020-07-27 01:31
Thanks for verifying this @stoeckmann; if the approach looks okay to @drakenclimber I'll submit a proper PR.

I did just do a force-push to address a problem with one of the regressions tests (test 11 was still expecting `seccomp_reset(NULL, ...)` to return an error).

**Comment by drakenclimber** [comment] 2020-07-27 14:50
> Thanks for verifying this @stoeckmann; if the approach looks okay to @drakenclimber I'll submit a proper PR.

I briefly looked through the proposed patch, and it seems like a reasonable solution to the problem.  Thanks for the fix.  I'll give it a closer look once you put out the PR.

**Comment by pcmoore** [comment] 2020-08-02 14:34
Proper PR time, see PR #280.

**Comment by poettering** [comment] 2020-08-04 08:25
(For context: systemd uses libseccomp heavily, most of its daemons come with a syscall filter enforced using libseccomp. All relevant filters ended up being disabled in stable f32 due to this bug, because we install the filters for each arch separately, as well as for each of our user-selectable configuration options separately, which means in effect on x86-64 only a tiny subset of the filters and only for the i386 syscall arch got installed, so that everything effectively is wide open. This bug is quite a biggie to us.)

**Comment by pcmoore** [comment] 2020-08-04 18:54
@poettering if this bug is a "biggie" for you on F32 stable, you might consider sticking with the v2.4.x release stream until the next v2.5.x release.  The libseccomp v2.4.x release is still supported and I believe @drakenclimber is planning on a new v2.4.x release soon.

**Comment by Conan-Kudo** [comment] 2020-08-04 22:34
@pcmoore I do not intend to roll back the libseccomp update. Please do the right thing and fix this in 2.5.x.

**Comment by pcmoore** [comment] 2020-08-04 22:43
@Conan-Kudo please read the PR and see we are.

**Comment by Conan-Kudo** [comment] 2020-08-04 22:46
@pcmoore Yup, sorry, I saw that later. Unfortunately this new GitHub UI makes it less obvious that there's a PR linked to an issue now...

**Comment by pcmoore** [comment] 2020-08-04 23:07
@Conan-Kudo well to be frank I was more concerned about the attitude that came across with those comments than the fact that you had missed the PR in progress.  This was a significant libseccomp release (v2.4.x -> v2.5.0) and there are bound to be bugs that aren't found until the release hits the major distros, if you rushed it from Rawhide into a Fedora stable release without sufficient testing with systemd, don't blame the upstream project.

**Comment by Conan-Kudo** [comment] 2020-08-04 23:33
I've had a pretty bad day of badgering from various people all day over this and other things.

As for "rushing" it, I did not do that. Since it was ABI compatible, I considered it safe to submit and didn't see anything obviously wrong when I tried it locally. I pushed it into Bodhi and let it sit for testing like everything else. It was given karma by other folks and made it to stable accordingly. This bug only showed up in the last day or so.

**Comment by pcmoore** [comment] 2020-08-05 00:25
> I've had a pretty bad day of badgering from various people all day over this and other things.

Then you should understand how your "I do not intend to roll back the libseccomp update. Please do the right thing and fix this in 2.5.x." comment sounds.

**Comment by Conan-Kudo** [comment] 2020-08-05 00:27
Yeah, yeah... I know. 😩 

Anyway, I've cherry-picked the PR into Fedora: https://src.fedoraproject.org/rpms/libseccomp/c/b7df1ffe6c217ba2fb9251b5b9c67f12040a68b5

**Comment by pcmoore** [comment] 2020-08-05 00:30
To elaborate a bit more, it's the "please do the right thing" that is especially grating.  It implies that we are intentionally trying to do the *wrong* thing, which is maddening when you consider the time and energy that goes into a release.

Listen, everybody hates it when stuff breaks, it sucks; it sucks doubly hard when you're overworked, burned out, and likely going through other stuff with this global pandemic.  Just assume we're upset it's broken too and we're trying to come up with a fix that doesn't screw things up worse - okay?

**Comment by Conan-Kudo** [comment] 2020-08-05 00:32
Yep, fine with me. I'll try to keep it in mind for the next time...

**Comment by pcmoore** [comment] 2020-08-05 00:32
> Anyway, I've cherry-picked the PR into Fedora: https://src.fedoraproject.org/rpms/libseccomp/c/b7df1ffe6c217ba2fb9251b5b9c67f12040a68b5

Okay, just buyer-beware that hasn't been merged yet, although there are no ABI changes so it should be safe'ish ... ?  Regardless, let us know how that goes; feedback on if it solves the problem for the Fedora crowd would be good.

**Comment by Conan-Kudo** [comment] 2020-08-05 00:33
Yeah, I figured that the severity of the unintended breakage would warrant pulling it in early and getting it evaluated to fix the issue we've hit.

**Closed** 2020-08-18 15:51 UTC
Labels: bug, priority/high
